import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ComparisonData, WeightedScore } from 'src/types'

export function usePdfExport() {
  function exportToPdf(data: ComparisonData, weightedScores: WeightedScore[]): void {
    const { comparison, items, criteria, scores } = data
    const orientation = items.length > 5 ? 'landscape' : 'portrait'
    const doc = new jsPDF({ orientation, unit: 'pt', format: 'a4' })

    // Title
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(comparison.title, 40, 40)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120)
    doc.text(`Generated by CompareTable — ${new Date().toLocaleDateString()}`, 40, 56)
    doc.setTextColor(0)

    // Build table head: Criterion | Weight | Item1 | Item2 | ...
    const head = [['Criterion', 'Weight', ...items.map((it) => it.name)]]

    // Body rows: one per criterion
    const body = criteria.map((cr) => {
      const weightStars = '★'.repeat(Math.round(cr.weight)) + '☆'.repeat(5 - Math.round(cr.weight))
      const cells = items.map((it) => {
        const s = scores.find((sc) => sc.itemId === it.id && sc.criterionId === cr.id)
        return s?.score !== null && s?.score !== undefined ? String(s.score) : '—'
      })
      return [cr.name, weightStars, ...cells]
    })

    // Total row
    const totalCells = items.map((it) => {
      const ws = weightedScores.find((w) => w.itemId === it.id)
      const score = ws ? ws.score.toFixed(1) : '—'
      const medal = ws?.rank === 1 ? ' 🥇' : ws?.rank === 2 ? ' 🥈' : ws?.rank === 3 ? ' 🥉' : ''
      return `${score}${medal}`
    })
    body.push(['WEIGHTED TOTAL', '', ...totalCells])

    autoTable(doc, {
      head,
      body,
      startY: 70,
      styles: { fontSize: 10, cellPadding: 6 },
      headStyles: { fillColor: [25, 118, 210], textColor: 255, fontStyle: 'bold' },
      columnStyles: { 0: { cellWidth: 140 }, 1: { cellWidth: 70, halign: 'center' } },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didParseCell: (data) => {
        if (data.row.index === criteria.length) {
          data.cell.styles.fontStyle = 'bold'
          data.cell.styles.fillColor = [232, 245, 233]
        }
      },
    })

    doc.save(`${comparison.title.replace(/[^a-z0-9]/gi, '_')}.pdf`)
  }

  return { exportToPdf }
}
